apiVersion: "acid.zalan.do/v1"
kind: OperatorConfiguration
metadata:
  name: {{ template "postgres-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "postgres-operator.name" . }}
    helm.sh/chart: {{ template "postgres-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
configuration:
  docker_image: {{ .Values.docker_image }}
  repair_period: {{ .Values.repair_period }}
  resync_period: {{ .Values.resync_period }}
  workers: {{ .Values.workers }}
{{ toYaml .Values.configCRD | indent 2 }}
  users:
{{ toYaml .Values.configUsers | indent 4 }}
  kubernetes:
    oauth_token_secret_name: {{ template "postgres-operator.fullname" . }}
    pod_service_account_name: operator
    spilo_privileged: {{ .Values.spilo_privileged }}
{{ toYaml .Values.configKubernetes | indent 4 }}
{{ toYaml .Values.configKubernetesCRD | indent 4 }}
  postgres_pod_resources:
{{ toYaml .Values.configPostgresPodResources | indent 4 }}
  timeouts:
{{ toYaml .Values.configTimeouts | indent 4 }}
  load_balancer:
{{ toYaml .Values.configLoadBalancerCRD | indent 4 }}
  aws_or_gcp:
{{ toYaml .Values.configAwsOrGcp | indent 4 }}
  logical_backup:
{{ toYaml .Values.configLogicalBackup | indent 4 }}
  debug:
{{ toYaml .Values.configDebug | indent 4 }}
  teams_api:
{{ toYaml .Values.configTeamsApiCRD | indent 4 }}
  logging_rest_api:
{{ toYaml .Values.configLoggingRestApi | indent 4 }}
  scalyr:
{{ toYaml .Values.configScalyr | indent 4 }}
