{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- if eq .Values.serviceAccount.name "" }}
            {{ template "postgres-operator.fullname" . }}
        {{- else }}
            {{ .Values.serviceAccount.name }}
        {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "postgres-operator.name" . }}
    helm.sh/chart: {{ template "postgres-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
